### ISSUE TITLE
Update NETN COM Documentation based on Input from Airbus

### ISSUE THREAD

**Issue by lofstrandbjorn** [AMSP-04/NETN-COM#5]
Update based on input from MSG-164.

**Comment by lofstrandbjorn** [comment]
Datatype TimeMillisecondsFloat32 used for Latency. Why Float?
There is a RPR-Base datatype TimeMillisecondUnsignedInteger32 is that ok to use?
Also, if we need a new Millisecond datatype is probably fits better in NETN-Base.

**Comment by lofstrandbjorn** [comment]
Datatypes Integer16 and Integer32 are already defined in RPR-Base. Remove?!

**Comment by ChristianPick** [comment]
Yes - remove them.

**Comment by ChristianPick** [comment]
> Datatype TimeMillisecondsFloat32 used for Latency. Why Float?
> There is a RPR-Base datatype TimeMillisecondUnsignedInteger32 is that ok to use?
> Also, if we need a new Millisecond datatype is probably fits better in NETN-Base.

We can start with TimeMillisecondsUnsignedInteger32. If we later see the resolution is not sufficient we could change then...

**Comment by lofstrandbjorn** [comment]
I propose the following changes to CommunicationNetwork attribute names:

CommunicationNetworkId -> UniqueId
CommunicationNetworkType -> NetworkType
CommunicationServiceType -> ServiceType and change Required->Optional

Add Divest & Acquire to all attributes (only to make it possible for federates to use ownership transfer, not a requirement).

Also for the datatype CommunicationServiceTypeEnum, we should perhaps explain the enumerations somewhere in the documentation. Do you have a list of the full name of the enums?

I propose the following Semantics for the CommunicationNetwork class. 
"The CommunicationNetwork class specifies details about the type of and service used by a logical communication network. This corresponds to the CommunicationNet-Elements of MSDL Units and Equipment. 
This object class should be considered as optional. No federate should rely on this data to work with communication networks."

**Comment by lofstrandbjorn** [comment]
For the Object Class "Node":

Propose Name change: Node->CommunicationNode

Proposed Attribute name change: OwnerId -> EntityReference (or EntityRef) or something similar (basically a reference to a Unit or an Equipment Item)
Proposed Attribute name change: Connections -> RequestedConnections

Not all Nodes may have a corresponding Aggregate of Physical entity represented in the federation at a given point in time. Aggregation, Deaggregation, Divide and Merge as defined in NETN-MRM may also change how Units (NETN-ORG) are represented in the simulation. The only things that are not changing are the Unit and Equipment Items as defined in MSDL and published in NETN-ORG. 


I propose the following change of the Semantics of the object class:
"A CommunicationNode is the representation of the interface of a unit or a piece of equipment to its communication networks. By referencing a simulated entity, a geographical location of the node can be derived. ...

**Comment by ChristianPick** [comment]
> CommunicationNetworkId -> NetworkId (Semantics "Required. Unique identifier for the communication network.")
> CommunicationNetworkType -> NetworkType (Semantics "Optional. The communication network type of use.")
> CommunicationServiceType -> ServiceType (Semantics "Optional. The type of service used on the communication network.")

The longer name might by annoying but helps to differentiate from the physical network. But feel free to change...

> Also for the datatype CommunicationServiceTypeEnum, we should perhaps explain the enumerations somewhere in the documentation. Do you have a list of the full name of the enums?

The enums were taken from MSDL. Maybe I can find something in the documentation there...

> I propose the following Semantics for the CommunicationNetwork class.
> "The CommunicationNetwork class specifies details about the type of and service used by a logical communication network. This corresponds to the CommunicationNet-Elements of MSDL Units and Equipment.
> This object class should be considered as optional. No federate should rely on this data to work with communication networks."

Fine for me.

**Comment by ChristianPick** [comment]
> For the Object Class "Node":
> 
> Propose Name change: Node->CommunicationNode

It was named CommunicationNode in my first draft - so if you prefer this rename it.

> Proposed Attribute name change: OwnerId -> EntityReference (or EntityRef) or something similar (basically a reference to a Unit or an Equipment Item)

OK.

> Proposed Attribute name change: Connections -> RequestedConnections

Isn't it named RequestedConnections? It should be...

> Not all Nodes may have a corresponding Aggregate of Physical entity represented in the federation at a given point in time. Aggregation, Deaggregation, Divide and Merge as defined in NETN-MRM may also change how Units (NETN-ORG) are represented in the simulation. The only things that are not changing are the Unit and Equipment Items as defined in MSDL and published in NETN-ORG.

**This has to be discussed. A node should have an entity (aggregate/physical) in place as the geographic location of the entity is needed to do the link simulation!**

> I propose the following change of the Semantics of the object class:
> "A CommunicationNode is the representation of the interface of a unit or a piece of equipment to its communication networks. By referencing a simulated entity, a geographical location of the node can be derived. ...

To be discussed...

**Comment by lofstrandbjorn** [comment]
> > Not all Nodes may have a corresponding Aggregate of Physical entity represented in the federation at a given point in time. Aggregation, Deaggregation, Divide and Merge as defined in NETN-MRM may also change how Units (NETN-ORG) are represented in the simulation. The only things that are not changing are the Unit and Equipment Items as defined in MSDL and published in NETN-ORG.
> 
> **This has to be discussed. A node should have an entity (aggregate/physical) in place as the geographic location of the entity is needed to do the link simulation!**
> 
> > I propose the following change of the Semantics of the object class:
> > "A CommunicationNode is the representation of the interface of a unit or a piece of equipment to its communication networks. By referencing a simulated entity, a geographical location of the node can be derived. ...
> 
> To be discussed...

We could require CommunicationNode objects always should have a corresponding Aggregate or PhysicalEntity but we just need to document what happens if/when these objects are added/removed from the simulation. Will the CommunicationNode be removed when the Aggregate/Physcial is removed from the federation? What will happen if the CommunicatioNode is referencing a non- existing entity?

**Comment by lofstrandbjorn** [comment]
> The enums were taken from MSDL. Maybe I can find something in the documentation there...

Found it.

**Comment by ChristianPick** [comment]
> We could require CommunicationNode objects always should have a corresponding Aggregate or PhysicalEntity but we just need to document what happens if/when these objects are added/removed from the simulation. Will the CommunicationNode be removed when the Aggregate/Physcial is removed from the federation? What will happen if the CommunicatioNode is referencing a non- existing entity?

A solution could be to add a "location" attribute to the CommunicationNode. If a valid EntityReference (to an existing entity) is given this wins, otherwise the location should be used. It is up to the owning federate of the CommunicationNode to set the location at least when the corresponding entity is unpublished. The NETN-COM module assumes the CommunicationNode is published / owned by the federate of the referenced entity, but this has to be discussed and documented either.

As the CommunicationNodes also describes devices within the physical network used for linking nodes it could be usefull to allow nodes without an entity but with the location only.

**Comment by lofstrandbjorn** [comment]
> A solution could be to add a "location" attribute to the CommunicationNode. If a valid EntityReference (to an existing entity) is given this wins, otherwise the location should be used. It is up to the owning federate of the CommunicationNode to set the location at least when the corresponding entity is unpublished. The NETN-COM module assumes the CommunicationNode is published / owned by the federate of the referenced entity, but this has to be discussed and documented either.
> 
> As the CommunicationNodes also describes devices within the physical network used for linking nodes it could be usefull to allow nodes without an entity but with the location only.

Yes I was thinking about this too. 

Semantics for the attribute EntityRef (new name) could be:

"Required: Reference by UUID to an existing object instance of one of the following classes:
- NETN-MRM Aggregate Entity
- NETN-Physical extensions of RPR Platforms and Lifeform object classes 

If the referenced entity exists in the federation, the location of the node is derived from the location of the entity.
If the referenced entity does not exist in the federation, the location of the node is defined by the optional location attribute. "

So if it is only the location we are really interested in we should perhaps just have one attribute Location with a Variant datatype for 1) Location by referencing an entity or 2) specified location. Or are there other attributes from the referenced entity that are of interest?

**Comment by ChristianPick** [comment]
Currently I see only the location to be relevant. As soon as there will be a link between NETN-COM and RPR-Communication and -DER there will be a need to have the entity in place as the embedded systems (transmitter/jammer etc) are referring to their host entity. We could avoid this by not using the RPR structure - but I'm not sure this would be a good idea.

**Comment by ChristianPick** [comment]
> So if it is only the location we are really interested in we should perhaps just have one attribute Location with a Variant datatype for 1) Location by referencing an entity or 2) specified location. Or are there other attributes from the referenced entity that are of interest?

As the EntityRef is invalid in case the location attribute should be used it does not make sense to use a location by referring the entity...

**Comment by ChristianPick** [comment]
Or did your meant to use the variant with the entity set instead of the EntityRef attribute? I think this would not be a good idea as the link to the entity will be lost as soon as the entity is unpublished. As the node represents a specific entity (regardless it is currently published or not) the reference should be in the data all time.

**Comment by lofstrandbjorn** [comment]
> Or did your meant to use the variant with the entity set instead of the EntityRef attribute? I think this would not be a good idea as the link to the entity will be lost as soon as the entity is unpublished. As the node represents a specific entity (regardless it is currently published or not) the reference should be in the data all time.

Agree. 

Proposal:

Change Semantics for EntityRef as:

"Required: Reference by UUID to an object instance of one of the following classes:

NETN-MRM Aggregate Entity
NETN-Physical extensions of RPR Platforms and Lifeform object classes
If the referenced entity exists in the federation, the location of the node is derived from the location of the entity.
If the referenced entity does not exist in the federation, the location of the node is defined by the Location attribute. "

Add attribute Location (datatype RPR WorldLocationStruct) with
semantics "Optional: Specifies the location of the CommunicationNode in case the entity referenced by EntityRef is not registered in the federation. If the entity referenced by EntityRef exists in the federation, the location of the communication node is derived from that entity and the value of the Location attribute shall be ignored."

**Comment by lofstrandbjorn** [comment]
Proposed updated semantics for CommunicationNode

"A CommunicationNode is the representation of the interface of a simulated entity to logical communication networks. The location of the CommunicationNode is derived from the referenced entity or specified explicitly (if the referenced entity is not registered in the federation). 

Connections to communication networks are established only if connectivity exists based on the status of available network devices and the simulation of links. Each potential connection is described in terms of requested connections  (the equivalent to the information provided by MSDL). "

**Comment by ChristianPick** [comment]
OK. Are you integrating the changes?

**Comment by lofstrandbjorn** [comment]
> OK. Are you integrating the changes?

Yes. I just pushed to edit branch.

**Comment by lofstrandbjorn** [comment]
Should the RequestedConnection and NetworkDevices attributes be Required or Optional?

Proposed semantics

RequestedConnections:
Optional. Possible (requested) connections for the communication node.

NetworkDevices:
Optional. Available network devices defining the association of a communication network (connection layer) with a physical network (link layer). Each network device can be associated with several communication networks but only to one physical network. Each network device also describes the transmitter and receiver capabilities.

**Comment by lofstrandbjorn** [comment]
In the OutgoingConnection class.

Is the SenderId a reference to an entity? The same entity as referenced in CommunicationNode? Rename to Sender, SenderEntity or SenderEntityRef?

Proposed Semantics for ConnectionId:
"Required. Unique identifier for the communication network connection."

Proposed Semantics for CommunicationNetworkId:
"Required. An identifier for the communication network this connection belongs to."

Proposed Semantics for SenderId:
"Required. A reference to the entity sending data using this connection."

Proposed Semantics for Receivers
"Required. Characteristics of the connections to individual receiving entities."

**Comment by lofstrandbjorn** [comment]
Fields of FixedRecord datatypes does not use Required/Optional. Only attributes and parameters can be optional or required. 

In datatype RequestedConnection:

Field: ConnectionId can not be Optional. Either it is always specified or it should be removed.

Field DestinationEntityIds. Semantics should be that an empty array indicates that no specific destinations are requested and that it is up to the federate publishing the OutgoingConnection object to determine Receivers. Should it be renamed ReceivingEntities?

Field NetworkDeviceId: Same as for ConnectionId. Either require or remove. Or we have to have a NULL UUID (all zeros) to indicate that a device is not specified.

**Comment by ChristianPick** [comment]
> Should the RequestedConnection and NetworkDevices attributes be Required or Optional?

Both are required.

> Is a RequestedConnection only related to OutgoingConnection?

No. By defining the type of connection this could be used to specify some kind of listener / interceptor. (E.g. AIS receiver). Not all requested connections are resulting in an OutgoingConnection object.

> 
> Proposed semantics
> 
> RequestedConnections:
> Optional. Possible (requested) connections for the communication node.
> 
> NetworkDevices:
> Optional. Available network devices defining the association of a communication network (connection layer) with a physical network (link layer). Each network device can be associated with several communication networks but only to one physical network. Each network device also describes the transmitter and receiver capabilities.

**Comment by ChristianPick** [comment]
> In the OutgoingConnection class.
> 
> Is the SenderId a reference to an entity? The same entity as referenced in CommunicationNode? Rename to Sender, SenderEntity or SenderEntityRef?

Yes. Rename it to SenderEntityRef as you renamed the attribute to EntityRef in the node.

> 
> Proposed Semantics for ConnectionId:
> "Required. Unique identifier for the communication network connection."
Add: ...This is the ConnectionId used in the corresponding connection request it it was set there.

> 
> Proposed Semantics for CommunicationNetworkId:
> "Required. An identifier for the communication network this connection belongs to."
OK

> 
> Proposed Semantics for SenderId:
> "Required. A reference to the entity sending data using this connection."
OK

> 
> Proposed Semantics for Receivers
> "Required. Characteristics of the connections to individual receiving entities."
OK

**Comment by ChristianPick** [comment]
> Fields of FixedRecord datatypes does not use Required/Optional. Only attributes and parameters can be optional or required.
> 
> In datatype RequestedConnection:
> 
> Field: ConnectionId can not be Optional. Either it is always specified or it should be removed.

It should be possible to set an invalid/undefined Id. We could use a "null"-Id for this cases...

> 
> Field DestinationEntityIds. Semantics should be that an empty array indicates that no specific destinations are requested and that it is up to the federate publishing the OutgoingConnection object to determine Receivers. Should it be renamed ReceivingEntities?

Semantics is OK, but I would not rename it ReceivingEntities as this is misleading. The receivers are determined by the communication simulation. E.g. radio messages could be received by entities they were not sent to.

> 
> Field NetworkDeviceId: Same as for ConnectionId. Either require or remove. Or we have to have a NULL UUID (all zeros) to indicate that a device is not specified.
Use the NULL UUID

**Comment by lofstrandbjorn** [comment]
> > In datatype RequestedConnection:
> > Field: ConnectionId can not be Optional. Either it is always specified or it should be removed.
> 
> It should be possible to set an invalid/undefined Id. We could use a "null"-Id for this cases...

Proposed semantics: 
"Requested Id for the connection. If no Id is requested the value of this field should be all zeros."

**Comment by lofstrandbjorn** [comment]
In datatype RequestedConnection:

Proposed semantics for Field "DestinationEntityIds": "List of entities intended as destinations for this requested connection."

Proposed semantics for Field "NetworkDeviceId": "Network Device for the requested connection. If no specific network device is requested the value of this field should be all zeros."

**Comment by ChristianPick** [comment]
> > > In datatype RequestedConnection:
> > > Field: ConnectionId can not be Optional. Either it is always specified or it should be removed.
> > 
> > 
> > It should be possible to set an invalid/undefined Id. We could use a "null"-Id for this cases...
> 
> Proposed semantics:
> "Requested Id for the connection. If no Id is requested the value of this field should be all zeros."

OK

**Comment by ChristianPick** [comment]
> In datatype RequestedConnection:
> 
> Proposed semantics for Field "DestinationEntityIds": "List of entities intended as destinations for this requested connection."
> 

Maybe it should be extended by "Leave empty in case of broadcasting or multicasting."

> Proposed semantics for Field "NetworkDeviceId": "Network Device for the requested connection. If no specific network device is requested the value of this field should be all zeros."

..."If no specific device is selected the communication simulation selects one by its internal rules."

**Comment by lofstrandbjorn** [comment]
> > In datatype RequestedConnection:
> > Proposed semantics for Field "DestinationEntityIds": "List of entities intended as destinations for this requested connection."
> 
> Maybe it should be extended by "Leave empty in case of broadcasting or multicasting."

fixed

**Comment by lofstrandbjorn** [comment]
> > Proposed semantics for Field "NetworkDeviceId": "Network Device for the requested connection. If no specific network device is requested the value of this field should be all zeros."
> 
> ..."If no specific device is selected the communication simulation selects one by its internal rules."

Added to general documentation on the use of NETN-COM but not as the semantics of the field.

**Comment by lofstrandbjorn** [comment]
Proposed semantics for PhysicalNetwork object class.

"This object class represents type-specific parameters/constraints for a physical network. Physical networks are simulated by LinkState objects and do not require that an instance of PhysicalNetwork exist in the federation. "

**Comment by lofstrandbjorn** [comment]
Missing fields and semantics for datatypes:

PhysicalRadioNetworkStruct
PhysicalSoundNetworkStruct
PhysicalLaserNetworkStruct

Could you come up with some first cut fields and definitions or should we remove them as variants of PhysicalNetworkDescriptionVariant?

**Comment by lofstrandbjorn** [comment]
PhysicalNetwork object class.

Proposal for:

Attribute: PhysicalNetworkId 
- Rename to NetworkId
- Semantics = "Required. Unique identifier for the communication network."

Attribute: Description
- Semantics "Required. Characteristics of the physical network."

**Comment by ChristianPick** [comment]
> Missing fields and semantics for datatypes:
> 
> PhysicalRadioNetworkStruct
> PhysicalSoundNetworkStruct
> PhysicalLaserNetworkStruct
> 
> Could you come up with some first cut fields and definitions or should we remove them as variants of PhysicalNetworkDescriptionVariant?

Remove them - we can add the variants later as needed. (same in TX/RX structures) For the moment we could start with the Generic variant.

**Comment by ChristianPick** [comment]
> PhysicalNetwork object class.
> 
> Proposal for:
> 
> Attribute: PhysicalNetworkId
> 
> * Rename to NetworkId
> * Semantics = "Required. Unique identifier for the communication network."

No. It's the ID of the physical network, not the communication network. To avoid misinterpretation I would prefer to name the attribute clearly as the PhysicalNetworkId.

> 
> Attribute: Description
> 
> * Semantics "Required. Characteristics of the physical network."

**Comment by lofstrandbjorn** [comment]
> > PhysicalNetwork object class.
> > Proposal for:
> > Attribute: PhysicalNetworkId
> > 
> > * Rename to NetworkId
> > * Semantics = "Required. Unique identifier for the communication network."
> 
> No. It's the ID of the physical network, not the communication network. To avoid misinterpretation I would prefer to name the attribute clearly as the PhysicalNetworkId.

But it is defined for the PhysicalNetwork object class so the attribute is already in the context of PhysicalNetwork. It is an attribute of that class and not a reference in which case it would be more natural to include the full name.

Also why not use a UnicodeString for this datatype?

**Comment by ChristianPick** [comment]
> > > PhysicalNetwork object class.
> > > Proposal for:
> > > Attribute: PhysicalNetworkId
> > > 
> > > * Rename to NetworkId
> > > * Semantics = "Required. Unique identifier for the communication network."
> > 
> > 
> > No. It's the ID of the physical network, not the communication network. To avoid misinterpretation I would prefer to name the attribute clearly as the PhysicalNetworkId.
> 
> But it is defined for the PhysicalNetwork object class so the attribute is already in the context of PhysicalNetwork. It is an attribute of that class and not a reference in which case it would be more natural to include the full name. The attribute PhysicalNetworkId on the LinkStates object class should be named PhysicalNetworkRef.

Renaming all references to "...Ref" instead of "...Id" is OK. In most (all?) SW projects / libraries I use it is common to name it the same, but of course it is reasonable to differ the role of the value by the name.
If "PhyscialNetworkId" is in the context of "PhysicalNetwork" than it would be consequent to reduce the name to "Id". The same for all other Ids in the module. Personally I don't like this naming scheme, but if you follow this design principle in all NETN modules it's OK.

> 
> Also why not use a UnicodeString for this datatype?

I just wanted a string - I didn't care about the exact type. Change it if you like.

**Comment by lofstrandbjorn** [comment]
I have cleaned up and added a lot of semantics where it was missing. I also added/changed the datatype UUID (a change that will be introduced throughout the NETN) instead of "UuidArrayOfHLAbyte16". I introduced the datatype in NETN-BASE but since we are running on baseline MAR 2020 I also added it to NETN-COM (to be removed at a later time). 

I am still struggling a bit with the Outgoing and Incoming Connection classes. Would one option be just to add an optional attribute to CommunicatioNode for incoming connections and rename OutgoingConnection to Connection?

**Comment by lofstrandbjorn** [comment]
An I propose to put a UniqueId (UUID) attribute in COM_Root and rename the attributes for Id in CommunicationNetwork and PhysicalNetwork to "UniqueName". UUID should always be generated but can be produced by the federate creating the object instance (autogenerate). UniqueName can be based on MSDL and used for reference.

**Comment by lofstrandbjorn** [comment]
I will push my local changes to the edit branch so you can view the latest.

**Comment by lofstrandbjorn** [comment]
Also, the Name of CommunicationNetwork has changed to datatype Text64 (unicode) which is used in NETN-ORG for MSDL text Ids. The datatype for the name of PhysicalNetwork is set to HLAunicodeString but it seems strange to use two different data types in the same module. Can/Should we limit the name of PhysicalNetwork to Text64? Or should we relax the datatype of CommunicationNetwork (conflict with MSDL)? Or keep as is? Suggestions? I propose to keep as is, or restrict PhysicalNetwork to Text64.

**Comment by ChristianPick** [comment]
> Also, the Name of CommunicationNetwork has changed to datatype Text64 (unicode) which is used in NETN-ORG for MSDL text Ids. The datatype for the name of PhysicalNetwork is set to HLAunicodeString but it seems strange to use two different data types in the same module. Can/Should we limit the name of PhysicalNetwork to Text64? Or should we relax the datatype of CommunicationNetwork (conflict with MSDL)? Or keep as is? Suggestions? I propose to keep as is, or restrict PhysicalNetwork to Text64.

I would keep the CommunicationNetwork-Id aligned to MSDL / NETN-ORG. I think Text64 would be sufficient for the PhysicalNetwork-Id, too.

**Comment by ChristianPick** [comment]
> I have cleaned up and added a lot of semantics where it was missing. I also added/changed the datatype UUID (a change that will be introduced throughout the NETN) instead of "UuidArrayOfHLAbyte16". I introduced the datatype in NETN-BASE but since we are running on baseline MAR 2020 I also added it to NETN-COM (to be removed at a later time).
> 
> I am still struggling a bit with the Outgoing and Incoming Connection classes. Would one option be just to add an optional attribute to CommunicatioNode for incoming connections and rename OutgoingConnection to Connection?

As the main reason for the Outgoing objects was load balancing and this is not the case for the IncomingConnections object it would be an alternative to have an attribute for the incoming connections. Still it has to be described in the federation agreement who is creating the data for this attribute. Personally I'm not a fan of ownership management as it could always be a burden to implement, depending on the SW architecture you use. Therefore I try to avoid to rely on this feature.

**Comment by ChristianPick** [comment]
> An I propose to put a UniqueId (UUID) attribute in COM_Root and rename the attributes for Id in CommunicationNetwork and PhysicalNetwork to "UniqueName". UUID should always be generated but can be produced by the federate creating the object instance (autogenerate). UniqueName can be based on MSDL and used for reference.

Could be done this way, but please describe in the semantics what "unique" mean for an UniqueName. Is it universally unique or only within its domain (communication/physical network). I would expect uniqueness within its domain.

**Comment by lofstrandbjorn** [comment]
I have completed my review and updates and pushed the changes to the edit branch. Unless there is anything else I will make a Pull Request to the develop branch and add a few reviewers.

**Comment by lofstrandbjorn** [comment]
This version now has 0 errors, 0 warnings, 0 info in Visual OMT.

**Comment by ChristianPick** [comment]
> This version now has 0 errors, 0 warnings, 0 info in Visual OMT.

Great work!

**Comment by lofstrandbjorn** [comment]
I added ChristianPick as a collaborator in the GitHub repo so I should be able to add you as a reviewer on the Pull Request. Accept the invite and I will first update some more of the documentation and then make a PR later today.
